title: Brandon Finley
description: Glaciology · Ice flow modeling · Scientific computing
url: "https://brandonfinley.me"
baseurl: ""

markdown: kramdown
kramdown:
  math_engine: mathjax

defaults:
  - scope:
      path: ""
    values:
      layout: default
